---
- id: CMD-0049
  key: kubernetesPKICertificateFilePermissions
  title: Kubernetes PKI certificate file permissions
  nodeType: master
  audit: stat -c %a $(ls -aR /var/lib/rancher/rke2/server/tls |
    awk'/:$/&&f{s=$0;f=0}/:$/&&!f{sub(/:$/,"");s=$0;f=1;next}NF&&f{print
    s"/"$0}' | grep \.crt$)
  platforms:
    - rke2
